/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2016-05-16 12:40:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LoginPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/ajinkyaja/Project/JspProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/CYBNETJSP/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098736290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1462858245406L));
    _jspx_dependants.put("jar:file:/C:/Users/ajinkyaja/Project/JspProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/CYBNETJSP/WEB-INF/lib/standard.jar!/META-INF/sql.tld", Long.valueOf(1098736290000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Login Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"cyan\" background=\"C:\\Users\\ajinkyaja\\Desktop\\wall.jpg\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("table{\r\n");
      out.write("\r\n");
      out.write("border-collapse: collapse;\r\n");
      out.write("margin: auto;\r\n");
      out.write("margin-top: 15%;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td{\r\n");
      out.write("border-collapse: collapse;\r\n");
      out.write("margin: auto;\r\n");
      out.write("margin-top: 15%;\r\n");
      out.write("padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnLogin, #btnExit\r\n");
      out.write("{\r\n");
      out.write("\twidth: 70px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tcolor: Red;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground-color: orange;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#btnLogin:HOVER {\r\n");
      out.write("\tbackground-color: cyan;\r\n");
      out.write("}\r\n");
      out.write("#btnExit:HOVER {\r\n");
      out.write("\tbackground-color: cyan;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<h1 align=\"center\" style=\"font-family: sans-serif;font-style: oblique;font-size-adjust: none;color: navy;\">Welcome to Cybage Book Review System</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"ResultPage.jsp\" style=\"richness: \" >\r\n");
      out.write("\r\n");
      out.write("<table style=\"width:25%\">\r\n");
      out.write("<tr>\r\n");
      out.write(" <td>UserName :  </td> <td><input type=\"text\" name=\"name\"></td><br>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr>\r\n");
      out.write(" <td>Password : </td> <td><input type=\"password\" name=\"pass\"></td><br>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr>\r\n");
      out.write(" <td>\r\n");
      out.write(" \r\n");
      out.write(" </td>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <td>\r\n");
      out.write(" <input id=\"btnLogin\" type=\"submit\" value=\"Login\">\r\n");
      out.write(" <input id=\"btnExit\" type=\"submit\" value=\"Exit\">\r\n");
      out.write(" \r\n");
      out.write(" </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" </table> \r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
